import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "white",
    },
    imageSkeleton: {
        height: 320,
        width: '100%',
        backgroundColor: '#E1E9EE',
    },
    buttonSkeleton: {
        backgroundColor: '#F2F8FC',
        borderRadius: 5,
        width: 40,
        height: 40,
    },
    titleSkeleton: {
        height: 38,
        width: '60%',
        backgroundColor: '#E1E9EE',
        marginBottom: 5,
    },
    subtextSkeleton: {
        height: 20,
        width: '40%',
        backgroundColor: '#E1E9EE',
    },
    descriptionIconSkeleton: {
        width: 32,
        height: 30,
        backgroundColor: '#E1E9EE',
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#E1E9EE',
    },
    descriptionTextSkeleton: {
        flex: 1,
        marginLeft: 10,
        backgroundColor: '#E1E9EE',
        margin: 5,
    },
    dateContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 16,
        borderWidth: 1,
        borderColor: '#E1E9EE',
        marginTop: 4,
        height: 30,
        borderRadius: 4,
    },
    dateIconSkeleton: {
        width: 32,
        height: 30,
        backgroundColor: '#E1E9EE',
        borderRightWidth: 1,
        borderColor: '#E1E9EE',
    },
    dateTextSkeleton: {
        width: 100,
        height: 19,
        backgroundColor: '#E1E9EE',
        marginLeft: 10,
    },
    picandvideoHeader: {
        height: 22,
        marginHorizontal: 16,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerTextSkeleton: {
        height: 22,
        width: 120,
        backgroundColor: '#E1E9EE',
    },
    thumbnailContainer: {
        marginTop: 4,
        marginLeft: 16,
    },
    thumbnailSkeleton: {
        width: 100,
        height: 100,
        backgroundColor: '#E1E9EE',
        marginRight: 2,
    },
    mapContainer: {
        marginTop: 16,
    },
    mapHeaderContainer: {
        marginHorizontal: 16,
        height: 30,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    mapHeaderSkeleton: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#E1E9EE',
        borderRadius: 4,
        flexDirection: 'row',
    },
    mapActionContainer: {
        flexDirection: 'row',
        gap: 4,
    },
    mapActionSkeleton: {
        width: 30,
        height: 30,
        backgroundColor: '#E1E9EE',
        borderRadius: 4,
    },
    mapViewSkeleton: {
        marginTop: 4,
        marginHorizontal: 16,
        height: 81,
        backgroundColor: '#E1E9EE',
        borderWidth: 1,
        borderColor: '#E1E9EE',
        borderRadius: 4,
    },
    addressContainer: {
        marginHorizontal: 16,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#E1E9EE',
        height: 30,
        flexDirection: 'row',
        borderTopWidth: 0,
    },
    addressIconSkeleton: {
        width: 32,
        height: 30,
        backgroundColor: '#E1E9EE',
        borderRightWidth: 1,
        borderColor: '#E1E9EE',
    },
    addressTextSkeleton: {
        flex: 1,
        marginLeft: 10,
        backgroundColor: '#E1E9EE',
        margin: 5,
    },
    shimmer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: '#FFFFFF',
        opacity: 0.3,
    },
    /////////////////////////////////////////////////////////main////////////////////////////////////////////
    bottom: {
        marginBottom: 200,
    },
    imageContainer: {
        position: "relative",
    },
    circle: {
        position: 'absolute',
        top: 7,
        left: 75,
    },
    image: {
        height: 320,
        width: "100%",
        resizeMode: "cover",
        justifyContent: "flex-end",
    },
    buttonContainer: {
        position: "absolute",
        top: 60,
        right: 30,
        flexDirection: "row",
        gap: 10,
    },
    button: {
        backgroundColor: "white",
        borderRadius: 5,
        alignContent: "center",
        alignItems: "center",
        justifyContent: "center",
        width: 40,
        height: 40,
    },
    rotatedIcon: {
        transform: [{ rotate: "45deg" }],
    },
    text: {
        color: "white",
        fontSize: 32,
        fontWeight: "600",
        position: "absolute",
        bottom: 25,
        left: 16,
    },
    subtext: {
        width: "40%",
        color: "white",
        fontSize: 16,
        fontWeight: "400",
        position: "absolute",
        bottom: 10,
        left: 16,
    },
    textContainer: {
    },
    //////////////////////////////////////////descriptionContainer//////////////////////
    skeletondescriptionContainer:{
        height:110,
        borderWidth: 1,
        marginHorizontal: 16,
        marginTop: 8,
        borderRadius: 4,
        borderColor: "#E1E9EE",
        flexDirection: "row",
    },
    descriptionContainer: {
        borderWidth: 1,
        marginHorizontal: 16,
        marginTop: 8,
        borderRadius: 4,
        borderColor: "#522F6080",
        flexDirection: "row",
    },
    descriptionIconsContainer: {
        alignItems: "center",
        justifyContent: "center",
        borderRightWidth: 1,
        borderBottomWidth: 1,
        height: 30,
        width: 32,
        borderColor: "#522F6080",
    },
    descriptionTextContainer: {
        flex: 1,
        marginLeft: 10,
    },
    descriptionText: {
        fontFamily: "Hiragino Sans",
        fontSize: 14,
        fontWeight: "300",
        lineHeight: 21,
        textAlign: "left",
    },
    descriptionIcons: {},
    descriptiontextContainer: {},
    //////////////////////////////////////////Date and Time //////////////////////////////////////////
    datecontainer: {
        flexDirection: "row",
        alignItems: "center",
        marginHorizontal: 16,
        borderWidth: 1,
        borderColor: "#522F6080",
        marginTop: 4,
        height: 30,
        borderRadius: 4,
    },
    DateTextContainer: {
        marginLeft: 10,
    },
    dateText: {
        fontFamily: "SF Pro",
        fontSize: 16,
        fontWeight: "400",
        lineHeight: 19.09,
        textAlign: "left",
        color: "#522F60",
    },
    //////////////////////////////////////////Pic and Video //////////////////////////////////////////
    picandvideoContainer: {
        marginTop: 16,
        borderRadius: 4,
        borderColor: "#522F6080",
        height: 146,
    },
    picandvideoHeaderContainer: {
        height: 22,
        marginHorizontal: 16,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    leftContent: {
        flexDirection: "row",
        alignItems: "center",
    },
    picandvideoHeadertext: {
        fontFamily: "Hiragino Sans",
        fontSize: 13,
        fontWeight: "600",
        lineHeight: 22,
        letterSpacing: 0.02,
        color: "#522F60",
    },
    picandvideoMainContainer: {
        marginTop: 4,
        marginLeft: 16,
    },
    picandvideo: {
        flexDirection: "row",
    },
    picandvideoImage: {
        width: 100,
        height: 100,
        marginHorizontal: 1,
    },
    picandvideoIcons: {},
    rightContent: {},
    picandvideoArrowIcons: {},
    icon: {},
    ///////////////////////////////////// Map ///////////////////////////////////////////
    MapContainer: {},
    MapIconsContainer: {
        alignItems: "center",
        justifyContent: "center",
        borderRightWidth: 1,
        height: 30,
        width: 32,
        borderColor: "#522F6080",
    },
    MapContainerHeader: {
        marginHorizontal: 16,
        height: 30,
        flexDirection: "row",
        justifyContent: "space-between",
    },
    actionHeaderContainer: {
        flexDirection: "row",
    },
    locationHeaderContainer: {
        borderRadius: 4,
        borderWidth: 1,
        borderColor: "#522F6080",
        flexDirection: "row",
        flex: 1
    },
    oneContent: {
        flexDirection: "row",
        alignItems: "center",
    },
    locationTextContainer: {
        marginLeft: 10,
    },
    locationHeadertext: {
        fontFamily: "SF Pro",
        fontSize: 16,
        fontWeight: "400",
        color: "#522F60",
    },
    twoContent: {
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 4,
        borderColor: "#522F6080",
        height: 30,
        width: 30,
        borderWidth: 1,
    },
    threeContent: {
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 4,
        borderColor: "#522F6080",
        height: 30,
        width: 30,
        borderWidth: 1,
    },
    fourContent: {
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 4,
        borderColor: "#522F6080",
        height: 30,
        width: 30,
        borderWidth: 1,
    },
    Mapicon: {},

    ////////////////////////////////
    mapSDKContainer: {
        marginTop: 4,
        marginHorizontal: 16,
        height: 81, // Increase height to make the map visible
        borderWidth: 1,
        borderColor: "#522F6080",
        borderRadius: 4,
    },
    fulladdress: {
        //marginTop:1,
        marginHorizontal: 16,
        borderRadius: 4,
        borderBottomWidth: 1,
        borderRightWidth: 1,
        borderLeftWidth: 1,
        borderColor: "#522F6080",
        height: 30,
        flexDirection: "row",
    },
    fulladdressTextContainer: {
        flex: 1,
        marginLeft: 10,
        justifyContent: "center",
    },
    fulladdressText: {
        fontFamily: "SF Pro",
        fontSize: 14,
        fontWeight: "200",
        color: "#522F60",
    },
});

export default styles;